### ISSUE TITLE
license

### ISSUE THREAD

**Issue by martinberoiz** [ryanoelkers/DIA#1]
Hi,
I'm interested in this code, I have something similar myself too, but it's not as solid as I'd liked it to be.
Are there any restrictions regarding forking and modifying the code?
May I suggest including a LICENSE.txt on the repo?

Thanks.

**Comment by ryanoelkers** [comment]
Hi! I don't necessarily have any problems with you forking the code, assuming you cite the appropriate papers in any work. I'll try to get a license.txt file up in the next week or so.

**Comment by martinberoiz** [comment]
Good! Thanks, I'll cite you appropriately.
