### ISSUE TITLE
-h --help command line option?

### ISSUE THREAD

**Issue by martinberoiz** [ryanoelkers/DIA#3]
Hi,

For oisdifference.c, it'd be nice to have a usage section printed when invoked with a `-h` or `--help`.
Would you be interested in a pull request adding this?

**Comment by ryanoelkers** [comment]
Sure, though there will be a pretty big update to the routines in the next week or so (some minor bug fixes and improved sub-routines), and I can just include that in the update.

**Comment by martinberoiz** [comment]
Good! that's great
