### ISSUE TITLE
core dumped problem

### ISSUE THREAD

**Issue by qnwang93** [ryanoelkers/DIA#5]
Hi 
I'm interested in this code. But when I try to run the c routine (a.out file) on my Linux PC, it gives "Segmentation fault (core dumped)". Is there any platform dependency of the code?

**Comment by ryanoelkers** [comment]
Usually when I have run into the "Segmentation fault (cord dumped)" issue it is because the parms.txt, ref.txt, img.txt, or refstars.txt are not appropriately generated. Are those text files in your working directory?

**Comment by martinberoiz** [comment]
I hope I'm not taking too much attributions, but I created a pull request to safeguard against NULL file pointers that can segfault for this specific case where a file is missing. Feel free to merge if you think it's safe.

**Comment by ryanoelkers** [comment]
great, thanks!
